//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JediWebApplication.JediWebService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JediContract", Namespace="http://schemas.datacontract.org/2004/07/JediService.Models")]
    [System.SerializableAttribute()]
    public partial class JediContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private JediWebApplication.JediWebService.CaracteristiqueContract[] CaracteristiquesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSithField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public JediWebApplication.JediWebService.CaracteristiqueContract[] Caracteristiques {
            get {
                return this.CaracteristiquesField;
            }
            set {
                if ((object.ReferenceEquals(this.CaracteristiquesField, value) != true)) {
                    this.CaracteristiquesField = value;
                    this.RaisePropertyChanged("Caracteristiques");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSith {
            get {
                return this.IsSithField;
            }
            set {
                if ((this.IsSithField.Equals(value) != true)) {
                    this.IsSithField = value;
                    this.RaisePropertyChanged("IsSith");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom {
            get {
                return this.NomField;
            }
            set {
                if ((object.ReferenceEquals(this.NomField, value) != true)) {
                    this.NomField = value;
                    this.RaisePropertyChanged("Nom");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CaracteristiqueContract", Namespace="http://schemas.datacontract.org/2004/07/JediService.Models")]
    [System.SerializableAttribute()]
    public partial class CaracteristiqueContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private JediWebApplication.JediWebService.EDefCaracteristiqueContract DefinitionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private JediWebApplication.JediWebService.ETypeCaracteristiqueContract TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ValeurField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public JediWebApplication.JediWebService.EDefCaracteristiqueContract Definition {
            get {
                return this.DefinitionField;
            }
            set {
                if ((this.DefinitionField.Equals(value) != true)) {
                    this.DefinitionField = value;
                    this.RaisePropertyChanged("Definition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom {
            get {
                return this.NomField;
            }
            set {
                if ((object.ReferenceEquals(this.NomField, value) != true)) {
                    this.NomField = value;
                    this.RaisePropertyChanged("Nom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public JediWebApplication.JediWebService.ETypeCaracteristiqueContract Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Valeur {
            get {
                return this.ValeurField;
            }
            set {
                if ((this.ValeurField.Equals(value) != true)) {
                    this.ValeurField = value;
                    this.RaisePropertyChanged("Valeur");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EDefCaracteristiqueContract", Namespace="http://schemas.datacontract.org/2004/07/JediService.Models")]
    public enum EDefCaracteristiqueContract : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Force = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Defense = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sante = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Chance = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ETypeCaracteristiqueContract", Namespace="http://schemas.datacontract.org/2004/07/JediService.Models")]
    public enum ETypeCaracteristiqueContract : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Jedi = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Stade = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StadeContract", Namespace="http://schemas.datacontract.org/2004/07/JediService.Models")]
    [System.SerializableAttribute()]
    public partial class StadeContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private JediWebApplication.JediWebService.CaracteristiqueContract[] CaracteristiquesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NbPlacesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlaneteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public JediWebApplication.JediWebService.CaracteristiqueContract[] Caracteristiques {
            get {
                return this.CaracteristiquesField;
            }
            set {
                if ((object.ReferenceEquals(this.CaracteristiquesField, value) != true)) {
                    this.CaracteristiquesField = value;
                    this.RaisePropertyChanged("Caracteristiques");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NbPlaces {
            get {
                return this.NbPlacesField;
            }
            set {
                if ((this.NbPlacesField.Equals(value) != true)) {
                    this.NbPlacesField = value;
                    this.RaisePropertyChanged("NbPlaces");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom {
            get {
                return this.NomField;
            }
            set {
                if ((object.ReferenceEquals(this.NomField, value) != true)) {
                    this.NomField = value;
                    this.RaisePropertyChanged("Nom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Planete {
            get {
                return this.PlaneteField;
            }
            set {
                if ((object.ReferenceEquals(this.PlaneteField, value) != true)) {
                    this.PlaneteField = value;
                    this.RaisePropertyChanged("Planete");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MatchContract", Namespace="http://schemas.datacontract.org/2004/07/JediService.Models")]
    [System.SerializableAttribute()]
    public partial class MatchContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdVainqueurField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private JediWebApplication.JediWebService.JediContract Jedi1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private JediWebApplication.JediWebService.JediContract Jedi2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private JediWebApplication.JediWebService.EPhaseTournoiContract PhaseTournoiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private JediWebApplication.JediWebService.StadeContract StadeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdVainqueur {
            get {
                return this.IdVainqueurField;
            }
            set {
                if ((this.IdVainqueurField.Equals(value) != true)) {
                    this.IdVainqueurField = value;
                    this.RaisePropertyChanged("IdVainqueur");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public JediWebApplication.JediWebService.JediContract Jedi1 {
            get {
                return this.Jedi1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Jedi1Field, value) != true)) {
                    this.Jedi1Field = value;
                    this.RaisePropertyChanged("Jedi1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public JediWebApplication.JediWebService.JediContract Jedi2 {
            get {
                return this.Jedi2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Jedi2Field, value) != true)) {
                    this.Jedi2Field = value;
                    this.RaisePropertyChanged("Jedi2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public JediWebApplication.JediWebService.EPhaseTournoiContract PhaseTournoi {
            get {
                return this.PhaseTournoiField;
            }
            set {
                if ((this.PhaseTournoiField.Equals(value) != true)) {
                    this.PhaseTournoiField = value;
                    this.RaisePropertyChanged("PhaseTournoi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public JediWebApplication.JediWebService.StadeContract Stade {
            get {
                return this.StadeField;
            }
            set {
                if ((object.ReferenceEquals(this.StadeField, value) != true)) {
                    this.StadeField = value;
                    this.RaisePropertyChanged("Stade");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EPhaseTournoiContract", Namespace="http://schemas.datacontract.org/2004/07/JediService.Models")]
    public enum EPhaseTournoiContract : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        QuartFinale = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DemiFinale = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Finale = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TournoiContract", Namespace="http://schemas.datacontract.org/2004/07/JediService.Models")]
    [System.SerializableAttribute()]
    public partial class TournoiContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private JediWebApplication.JediWebService.MatchContract[] MatchsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public JediWebApplication.JediWebService.MatchContract[] Matchs {
            get {
                return this.MatchsField;
            }
            set {
                if ((object.ReferenceEquals(this.MatchsField, value) != true)) {
                    this.MatchsField = value;
                    this.RaisePropertyChanged("Matchs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom {
            get {
                return this.NomField;
            }
            set {
                if ((object.ReferenceEquals(this.NomField, value) != true)) {
                    this.NomField = value;
                    this.RaisePropertyChanged("Nom");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="JediWebService.IJediWebService")]
    public interface IJediWebService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJediWebService/GetJedis", ReplyAction="http://tempuri.org/IJediWebService/GetJedisResponse")]
        JediWebApplication.JediWebService.JediContract[] GetJedis();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJediWebService/GetJedis", ReplyAction="http://tempuri.org/IJediWebService/GetJedisResponse")]
        System.Threading.Tasks.Task<JediWebApplication.JediWebService.JediContract[]> GetJedisAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJediWebService/CreateJedi", ReplyAction="http://tempuri.org/IJediWebService/CreateJediResponse")]
        void CreateJedi(JediWebApplication.JediWebService.JediContract jedi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJediWebService/CreateJedi", ReplyAction="http://tempuri.org/IJediWebService/CreateJediResponse")]
        System.Threading.Tasks.Task CreateJediAsync(JediWebApplication.JediWebService.JediContract jedi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJediWebService/GetStades", ReplyAction="http://tempuri.org/IJediWebService/GetStadesResponse")]
        JediWebApplication.JediWebService.StadeContract[] GetStades();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJediWebService/GetStades", ReplyAction="http://tempuri.org/IJediWebService/GetStadesResponse")]
        System.Threading.Tasks.Task<JediWebApplication.JediWebService.StadeContract[]> GetStadesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJediWebService/GetMatchs", ReplyAction="http://tempuri.org/IJediWebService/GetMatchsResponse")]
        JediWebApplication.JediWebService.MatchContract[] GetMatchs();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJediWebService/GetMatchs", ReplyAction="http://tempuri.org/IJediWebService/GetMatchsResponse")]
        System.Threading.Tasks.Task<JediWebApplication.JediWebService.MatchContract[]> GetMatchsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJediWebService/GetTournois", ReplyAction="http://tempuri.org/IJediWebService/GetTournoisResponse")]
        JediWebApplication.JediWebService.TournoiContract[] GetTournois();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJediWebService/GetTournois", ReplyAction="http://tempuri.org/IJediWebService/GetTournoisResponse")]
        System.Threading.Tasks.Task<JediWebApplication.JediWebService.TournoiContract[]> GetTournoisAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJediWebService/GetCaracteristiques", ReplyAction="http://tempuri.org/IJediWebService/GetCaracteristiquesResponse")]
        JediWebApplication.JediWebService.CaracteristiqueContract[] GetCaracteristiques(JediWebApplication.JediWebService.JediContract jedi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJediWebService/GetCaracteristiques", ReplyAction="http://tempuri.org/IJediWebService/GetCaracteristiquesResponse")]
        System.Threading.Tasks.Task<JediWebApplication.JediWebService.CaracteristiqueContract[]> GetCaracteristiquesAsync(JediWebApplication.JediWebService.JediContract jedi);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IJediWebServiceChannel : JediWebApplication.JediWebService.IJediWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class JediWebServiceClient : System.ServiceModel.ClientBase<JediWebApplication.JediWebService.IJediWebService>, JediWebApplication.JediWebService.IJediWebService {
        
        public JediWebServiceClient() {
        }
        
        public JediWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public JediWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JediWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JediWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public JediWebApplication.JediWebService.JediContract[] GetJedis() {
            return base.Channel.GetJedis();
        }
        
        public System.Threading.Tasks.Task<JediWebApplication.JediWebService.JediContract[]> GetJedisAsync() {
            return base.Channel.GetJedisAsync();
        }
        
        public void CreateJedi(JediWebApplication.JediWebService.JediContract jedi) {
            base.Channel.CreateJedi(jedi);
        }
        
        public System.Threading.Tasks.Task CreateJediAsync(JediWebApplication.JediWebService.JediContract jedi) {
            return base.Channel.CreateJediAsync(jedi);
        }
        
        public JediWebApplication.JediWebService.StadeContract[] GetStades() {
            return base.Channel.GetStades();
        }
        
        public System.Threading.Tasks.Task<JediWebApplication.JediWebService.StadeContract[]> GetStadesAsync() {
            return base.Channel.GetStadesAsync();
        }
        
        public JediWebApplication.JediWebService.MatchContract[] GetMatchs() {
            return base.Channel.GetMatchs();
        }
        
        public System.Threading.Tasks.Task<JediWebApplication.JediWebService.MatchContract[]> GetMatchsAsync() {
            return base.Channel.GetMatchsAsync();
        }
        
        public JediWebApplication.JediWebService.TournoiContract[] GetTournois() {
            return base.Channel.GetTournois();
        }
        
        public System.Threading.Tasks.Task<JediWebApplication.JediWebService.TournoiContract[]> GetTournoisAsync() {
            return base.Channel.GetTournoisAsync();
        }
        
        public JediWebApplication.JediWebService.CaracteristiqueContract[] GetCaracteristiques(JediWebApplication.JediWebService.JediContract jedi) {
            return base.Channel.GetCaracteristiques(jedi);
        }
        
        public System.Threading.Tasks.Task<JediWebApplication.JediWebService.CaracteristiqueContract[]> GetCaracteristiquesAsync(JediWebApplication.JediWebService.JediContract jedi) {
            return base.Channel.GetCaracteristiquesAsync(jedi);
        }
    }
}
